import type { Layer, Technique } from './types'

export const layerLabels: Record<Layer, string> = {
  infra: 'Infraestrutura',
  mundos: 'Mundos e cenas',
  transicoes: 'Revelações e transições',
  imagem: 'Imagem e superfície',
  nossas: 'Do próprio portfólio',
}

/**
 * As 16 técnicas do catálogo v1, na ordem do documento. Cada uma segue o
 * formato Problema → Mecanismo → Quando NÃO usar. Um componente não é uma
 * técnica: só entra o que explica o mecanismo e transfere para outro projeto.
 */
export const tecnicas: readonly Technique[] = [
  {
    id: 'I.1',
    layer: 'infra',
    stars: 3,
    title: 'Composite rendering',
    problem: 'Renderizar direto para a tela é um beco sem saída: não dá para transicionar entre cenas nem sobrepor camadas independentes.',
    mechanism: 'São dois passes: a cena renderiza para um WebGLRenderTarget em vez do canvas, e a textura resultante vira material de um quad de tela cheia numa segunda cena, com um shader no meio. Isso desacopla o conteúdo da cena da sua apresentação. Com duas cenas em dois render targets, uma transição vira simplesmente um mix(texA, texB, progress).',
    whenNot: 'Cena única, sem transição nem post-processing — o pass extra não se paga.',
    source: 'https://tympanus.net/codrops/2026/02/23/composite-rendering-the-brilliance-behind-inspiring-webgl-transitions/',
  },
  {
    id: 'I.2',
    layer: 'infra',
    stars: 3,
    title: 'Sincronizar DOM ↔ WebGL (1px = 1 unidade)',
    problem: 'Shader sobre conteúdo que vive no HTML, mantendo layout e scroll. Posicionar planos 3D no olho nunca fecha.',
    mechanism: 'Escolha o FOV em função da altura, com a câmera em z = 100: a altura visível passa a ser exatamente window.innerHeight em pixels, e um mesh de escala 800×1000 mede 800×1000 pixels na tela. As posições vêm de getBoundingClientRect() convertidas para o sistema centrado do WebGL, sempre subtraindo o scroll. Meça todos os elementos uma vez por frame, antes de aplicar transforms, ou o reflow síncrono come o frame.',
    whenNot: 'Cena 3D de verdade, que não tem contraparte no DOM. Se o projeto for só isso, o curtains.js já entrega a mesma ideia pronta.',
    source: 'https://tympanus.net/codrops/2026/02/19/creating-a-smooth-horizontal-parallax-gallery-from-dom-to-webgl/',
  },
  {
    id: 'I.3',
    layer: 'infra',
    stars: 3,
    title: 'Um ticker só para tudo',
    problem: 'GSAP, Lenis, three.js e Web Audio, cada um com seu requestAnimationFrame, brigam por timing e geram judder indebugável.',
    mechanism: 'O ticker do GSAP dirige tudo: o Lenis é acionado a partir dele e o render do three sai de updates do ScrollTrigger, não de um loop contínuo próprio. A comunicação entre camadas passa por valores de progresso normalizados de 0 a 1 como estado compartilhado, e cada componente deriva sua faixa local. Fontes concorrentes — scroll, hover, segurar o clique — se combinam por Math.max() em vez de caminhos de animação paralelos.',
    whenNot: 'Cena isolada, que não divide timing com scroll, tween ou áudio: aí o loop do próprio renderer já é o ticker único. Abrir mão do React Three Fiber para ter esse controle é um trade-off real e custa ergonomia.',
    source: 'https://tympanus.net/codrops/2026/07/15/the-architecture-behind-trionn-coordinating-gsap-three-js-lenis-and-web-audio/',
  },
  {
    id: 'I.4',
    layer: 'infra',
    stars: 2,
    title: 'Ping-pong FBO',
    problem: 'Efeitos com memória — fluido, trilha, difusão — precisam do frame anterior, e um shader não lê e escreve a mesma textura.',
    mechanism: 'Dois render targets trocam de papel a cada frame: A guarda o estado anterior, o shader lê A, aplica difusão ou deslocamento e escreve em B, e então A e B trocam. No caso do fluido, o frame anterior é amostrado em cinco posições — o próprio pixel e quatro vizinhos deslocados por ruído — com blending darken; somar um pouco de branco a cada frame, com clamp em 1.0, faz o rastro sumir sozinho quando o cursor para.',
    whenNot: 'Efeito sem estado. Se cada frame é função só do tempo, isso é uniform, não FBO.',
  },
  {
    id: 'II.1',
    layer: 'mundos',
    stars: 2,
    title: 'Chunking: infinito com três segmentos',
    problem: 'Um corredor ou mundo infinito não cabe na memória, e modelar quilômetros no Blender não é viável.',
    mechanism: 'Só três segmentos ficam montados — o da câmera, um à frente e um atrás — criados e destruídos por um manager conforme ela avança no eixo Z. Um wrapper de visibilidade checa frame a frame e some com o segmento inteiro 5 unidades depois, zerando draw calls para o que a câmera nem olha. Para um mundo navegável em duas dimensões, a variante é um único chunk repetido numa grade 3×3 que reposiciona ao cruzar a fronteira: nove chunks em memória, independente do tamanho do mundo.',
    whenNot: 'Mundo pequeno o bastante para ficar montado inteiro. As costuras precisam fechar em UV e geometria — qualquer desalinhamento salta aos olhos, e esse custo não se paga sem o que streamar.',
    source: 'https://tympanus.net/codrops/2026/06/11/sketching-the-impossible-a-3d-portfolio-built-without-a-single-3d-model/',
  },
  {
    id: 'II.2',
    layer: 'mundos',
    stars: 2,
    title: 'Fog animado por injeção de shader',
    problem: 'O fog nativo do three é linear e morto. Atmosfera de verdade se move.',
    mechanism: 'Via onBeforeCompile() no material que já existe, dois passos: primeiro um fog por posição de mundo, em que acima de certo Y a cor fica intacta e abaixo vira a cor do fog, com smoothstep na transição; depois a animação, por uma textura de ruído seamless deslocada no tempo, com domain warping distorcendo a superfície. É barato porque reaproveita uma textura em vez de calcular Perlin por fragment — uma amostra por material.',
    whenNot: 'Cena com muitos polígonos e materiais, já que a injeção entra em todos eles. Frequência e velocidade mal calibradas também deixam a repetição da textura óbvia.',
  },
  {
    id: 'II.3',
    layer: 'mundos',
    stars: 1,
    title: 'Contorno por inverted hull',
    problem: 'Contorno de malha estilo cel-shading ou desenho, sem um pass de post-processing.',
    mechanism: 'Duplica-se a geometria com as normais invertidas e deslocada para fora, com material preto. O trabalho é feito no Blender, não em runtime: modificador Solidify com espessura negativa, normais invertidas e offset de material apontando para o slot do contorno; exporta aplicando os modificadores e, no JS, reatribui para MeshBasicMaterial. Nada acontece por frame — só há geometria a mais renderizada uma vez.',
    whenNot: 'Muitos objetos em cena: dobra a contagem de triângulos. Nesse caso vale um pass de post baseado em normal e depth.',
  },
  {
    id: 'III.1',
    layer: 'transicoes',
    stars: 2,
    title: 'Máscara de threshold',
    problem: 'Transição de tela cheia que não seja um crossfade genérico.',
    mechanism: 'Uma textura preto-e-branco funciona como threshold por pixel: um uniform uProgress anima de 0 a 1 e cada fragment vira quando o progresso ultrapassa o valor daquele pixel — basicamente um step() por fragment. Trocar a textura troca a transição inteira, de espiral a ondas a listras, sem tocar no shader. Custa uma amostra de textura e aritmética simples, em pass único.',
    whenNot: 'Se a única máscara disponível for de baixa resolução, porque o banding fica visível. A curva do progresso também precisa de ajuste, ou o movimento não parece natural.',
  },
  {
    id: 'III.2',
    layer: 'transicoes',
    stars: 2,
    title: 'X-ray reveal com fluido',
    problem: 'Revelar uma segunda camada seguindo o cursor de forma orgânica, em vez de abrir um círculo duro sobre a cena.',
    mechanism: 'Combina composite rendering e ping-pong FBO. Duas cenas — corpo sólido e esqueleto — compartilham câmera e luz, cada uma no seu render target. A máscara nasce de um rastro circular que o cursor desenha num canvas, alimenta uma simulação de fluido difundida para fora e modulada por ruído FBM, e no post é invertida para servir de fator de mix entre as duas cenas.',
    whenNot: 'Quando um gradiente radial resolve. A simulação de fluido custa dois FBOs por frame.',
    source: 'https://tympanus.net/codrops/2026/03/23/building-a-dual-scene-fluid-x-ray-reveal-effect-in-three-js/',
  },
  {
    id: 'III.3',
    layer: 'transicoes',
    stars: 3,
    title: 'Cena WebGL persistente entre páginas',
    problem: 'Navegar entre páginas destrói o contexto WebGL: recarrega modelo, recompila shader, pisca.',
    mechanism: 'O canvas fica fora do container que o roteador troca, então só o HTML de dentro é reconstruído: canvas, renderer, cena, luzes, modelos já carregados e estado do mouse sobrevivem à navegação. O objeto de experiência precisa ser singleton, criado no hook de inicialização e reusado depois, e os modelos são clonados, nunca recarregados. A câmera anima em paralelo com a transição de conteúdo, dirigida por um mapa de rota para posição — é isso que dá coesão.',
    whenNot: 'Site de página única, em que não há navegação a preservar e a complexidade do singleton não se paga.',
    source: 'https://tympanus.net/codrops/2026/03/18/building-seamless-3d-transitions-with-webflow-gsap-and-three-js/',
  },
  {
    id: 'IV.1',
    layer: 'imagem',
    stars: 3,
    title: 'Reacender foto 2D com depth map',
    problem: 'Fazer uma foto comum reagir à luz e ao cursor como se tivesse relevo, sem modelar nada em 3D.',
    mechanism: 'Três peças sobre um plano chato: um depth map gerado por modelo de estimativa de profundidade, normais calculadas a partir dele — a inclinação vem da textura, não da geometria, e só isso já faz o plano responder à luz como se tivesse volume — e sombras por ray march, em que cada pixel traça uma linha até a luz atravessando o depth map. Converta o depth de 8 bits para float e borre antes de usar: 256 valores viram ruído granulado quando a luz lê a inclinação.',
    whenNot: 'Quando um elemento precisa projetar sombra em outro: existe só auto-oclusão. O ray march custa GPU e o realismo depende inteiramente da qualidade da estimativa de profundidade.',
    source: 'https://tympanus.net/codrops/2026/08/19/relighting-images-with-depth-maps-and-three-js/',
  },
  {
    id: 'V.1',
    layer: 'nossas',
    stars: 3,
    title: 'Depth prepass para nuvem de pontos aditiva',
    problem: 'Sprites aditivos sem depthWrite não se ocluem: o fundo soma através da frente e o meio da silhueta vira a região mais clara.',
    mechanism: 'Uma malha decimada e invisível do mesmo objeto é desenhada antes, com colorWrite desligado e depthWrite ligado: nenhum pixel muda de cor, mas a superfície próxima entra no depth buffer e o depthTest normal da nuvem descarta cerca de 70% dos pontos. Um draw call, zero fill. O hull precisa ser encolhido uns 4% do raio pelas próprias normais, senão engole as reentrâncias que deveria revelar. A luz economizada permitiu dobrar a contagem de pontos.',
    whenNot: 'Nuvem esparsa, em que o lado de trás não soma o bastante para lavar a silhueta — aí é um draw call a mais por nada.',
    source: 'portfolio-3d/src/three/BrainCloud.tsx',
  },
  {
    id: 'V.2',
    layer: 'nossas',
    stars: 3,
    title: 'Beats ancorados no DOM',
    problem: 'Coreografia de scroll com posições cravadas quebra em silêncio: um card a mais em qualquer lugar acima desalinha tudo.',
    mechanism: 'Inverte quem sabe a posição: a seção entrega um elemento DOM ao registro, e um ResizeObserver converte esse elemento em progresso de 0 a 1. Ele observa também o documentElement, porque algo crescendo acima move o beat sem redimensioná-lo, e as medições são coalescidas num rAF. Em React, o store é de módulo e não context — o consumidor vive dentro do canvas, que tem reconciliador próprio, e o valor é lido 60 vezes por segundo.',
    whenNot: 'Animação que não tem relação com o conteúdo da página, como uma intro cronometrada: não há âncora a que prender o beat.',
    source: 'portfolio-3d/src/three/beats.ts',
  },
  {
    id: 'V.3',
    layer: 'nossas',
    stars: 2,
    title: 'Damping assimétrico',
    problem: 'Uma taxa de damping só não consegue ser rápida na perseguição e macia no assentamento.',
    mechanism: 'A taxa vira função da distância até o alvo, não do tempo de frame: interpola entre uma taxa de assentamento e uma de perseguição por um smoothstep sobre a distância restante. No portfólio isso cortou uma troca de lado de 0,90 s para 0,27 s sem perder a maciez, e como continua sendo damp exponencial segue independente de frame rate.',
    whenNot: 'Alvo que muda pouco ou distância sempre curta: um damp de taxa fixa já resolve, com um parâmetro a menos para justificar.',
    source: 'portfolio-3d/src/three/ScrollStage.tsx',
  },
  {
    id: 'V.4',
    layer: 'nossas',
    stars: 2,
    title: 'Cursor como raio, não como ponto',
    problem: 'Repulsão medida até o cursor projetado num plano só afeta a fatia do objeto perto daquele plano.',
    mechanism: 'Guarde a direção do cursor em view space dividida pela própria profundidade. Multiplicada pelo z do ponto, ela dá onde o raio passa naquela profundidade — a profundidade se cancela na conta. A influência vira um cilindro em torno do raio em vez de uma esfera em torno de um ponto dele, e por estar em view space é imune a qualquer transform aplicado ao grupo.',
    whenNot: 'Objeto chato ou concentrado num plano só, em que a distância até um ponto já cobre a geometria inteira.',
    source: 'portfolio-3d/src/three/shaders/brainCloud.ts',
  },
  {
    id: 'V.5',
    layer: 'nossas',
    stars: 2,
    title: 'Quantização Int16 normalizada',
    problem: 'Buffers de geometria em Float32 são o download da página.',
    mechanism: 'Grave os atributos em Int16 e entregue com normalized: true — a GPU divide por 32767 no fetch do atributo, de graça, e não existe passe de decode. 48k pontos com posição, normal e curvatura ocupam 659 KB em Int16 contra 1,3 MB em Float32, e a precisão não é problema: o quantum é cerca de 700× menor que o espaçamento entre vizinhos. Combinado com um shuffle determinístico no build, escalar por dispositivo vira um setDrawRange.',
    whenNot: 'Buffer pequeno, em que o download não é o gargalo: a quantização adiciona um passo de build sem ganho perceptível.',
    source: 'portfolio-3d/scripts/build-brain-pointcloud.ts',
  },
]
